#!/bin/bash
#
DOCROOT=`grep -Po '^chdir = \K.*' /etc/php-fpm.d/www.conf 2>/dev/null`
if [ -z ${DOCROOT} ];then
	DOCROOT="/usr/local/emhttp"
fi

# Copy config files to ram file system.
${DOCROOT}/plugins/unraid.usbip-gui/scripts/copy_config.sh

#logger "Mounting 'Auto Mount' Devices..." -t"unassigned.devices"
#${DOCROOT}/plugins/unraid.usbip-gui/scripts/rc.unraid,.usbip-gui mount autodevices
