#!/bin/bash
#
DOCROOT=`grep -Po '^chdir = \K.*' /etc/php-fpm.d/www.conf 2>/dev/null`
if [ -z ${DOCROOT} ];then
	DOCROOT="/usr/local/emhttp"
fi

logger "Detach All USBIP Devices..." -t"unraid.usbip-gui"
${DOCROOT}/plugins/unraid.usbip-gui/scripts/rc.unraid.usbip-gui disconnect all
